apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  namespace: austin-spin-ftw
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
        - command:
            - echo
            - SPINNAKER_PROPERTY_TEST=123
          image: 'perl:5.34.0'
          name: pi
      restartPolicy: Never
