{
    "application": "test",
    "name": "First Dinghyfile Pipeline",
    "keepWaitingPipelines": false,
    "limitConcurrent": true,
    "stages": [{
      "name": "Wait",
      "refId": "1",
      "requisiteStageRefIds": [
        "2"
      ],
      "type": "wait",
      "waitTime": 19
    },
    {
      "name": "Wait",
      "refId": "2",
      "requisiteStageRefIds": [],
      "type": "wait",
      "waitTime": 23
    }],
    "triggers": []
}
